name: Deploy DotNet project to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: b2c-ipification-demo
  AZURE_WEBAPP_PROJECT_PATH: './src/B2C.IPificationDemo.csproj'
  AZURE_WEBAPP_OUTPUT_PATH: './output'
  DOTNET_VERSION: '2.2.402'
  DEMO_APP_CLIENT_ID: 01622107-38b3-4a2c-9701-526641cdfdcf

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Replace tokens in appsettings.json
      uses: cschleiden/replace-tokens@v1.0
      with:
        tokenPrefix: "{"
        tokenSuffix: "}"
        files: "src/appsettings.json"
      env:
        DemoApplicationClientId: ${{ env.DEMO_APP_CLIENT_ID }}
        DemoApplicationClientSecret: ${{ secrets.DEMO_APP_CLIENT_SECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    
    - name: dotnet build and publish
      run: |
        dotnet build '${{ env.AZURE_WEBAPP_PROJECT_PATH }}' --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_OUTPUT_PATH }}' 
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: '${{ env.AZURE_WEBAPP_OUTPUT_PATH }}'